"""
OpenAI-based editing functionality for SEAL.
This module provides integration with OpenAI's API for generating text edits.
"""
import os
from typing import Optional

import openai

def generate_edit_via_openai(text: str, model: str = "gpt-4") -> str:
    """
    Generate an edit for the given text using the OpenAI API.
    
    Args:
        text: The input text to be edited
        model: The OpenAI model to use for generation (default: "gpt-4")
        
    Returns:
        The edited text generated by the model
        
    Raises:
        ValueError: If OPENAI_API_KEY is not set in the environment
        openai.OpenAIError: For any API-related errors
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError(
            "OPENAI_API_KEY environment variable not found. "
            "Please set it with your OpenAI API key to use this feature."
        )
    
    client = openai.OpenAI(api_key=api_key)
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "Improve factual accuracy and clarity."},
                {"role": "user", "content": f"Edit this: {text}"}
            ],
            temperature=0.7,
            max_tokens=2000
        )
        
        return response.choices[0].message.content.strip()
    except Exception as e:
        # Log the error and re-raise with a more descriptive message
        error_msg = f"Error generating edit with OpenAI: {str(e)}"
        print(error_msg)
        raise
